services:
  php:
    container_name: aupf_php
    build:
      context: .docker/php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/php/logs:/var/log
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/config/apache2.conf:/etc/apache2/apache2.conf
    links:
      - db
    restart: always
    networks:
      - docker_default

  db:
    container_name: aupf_db
    platform: linux/amd64
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./.docker/db/config/mysql_custom.conf:/etc/mysql/conf.d/mysql_custom.conf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - docker_default

networks:
  docker_default:
    external: true
